### ISSUE TITLE
MsBuild usage

### ISSUE THREAD

**Issue by jovball** [Epsilekt/T4Executer#1]
Can this be used with MSBuild on a build server? If so, how would it be configured?

**Comment by Epsilekt** [comment]
This is an extension for Visual Studio on your local machine. You cannot
configure TExecuter to run templates on a build server.

I can try an create a nuget package that you can use in your build pipeline
to achieve what you want.


Kind regards

Op za 18 mei 2019 om 03:52 schreef jovball <notifications@github.com>:

**Comment by ite-klass** [comment]
To spread some knowledge, in case users come here looking for it:

@jovball you can use MSBuild itself to transform the templates on build, in general, if outdated, and also specific files only.

In your project file import the `TextTemplating\Microsoft.TextTemplating.targets` file, and then use the properties and Transform target as desired and as documented in the targets file.
