### ISSUE TITLE
Have Config file in code

### ISSUE THREAD

**Issue by jon49** [Epsilekt/T4Executer#2]
Would it be possible to have a config file in code (like maybe a csproj file) that the extension can use so the settings can be shared across a whole team?

**Comment by Epsilekt** [comment]
Yes, this is possible. First thing that comes to mind is a Json file or a XML on solution folder level. 

I can implement this next week, a little busy at the moment!

**Comment by jon49** [comment]
No need to update the code. We're going with a different solution. Great extension though! If someone else needs this functionality then maybe it would be good to still do something! Thanks for being so quick to respond!

**Comment by Epsilekt** [comment]
No problem!
